package pl.devzyra.model.dto;

import lombok.*;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@AllArgsConstructor
public class UserDto implements Serializable {

    private static final long serialVersionUID = 1836044288747480188L;

    private Long id;                // sensitive DB id
    private String userId;          // safely shared id generated by Utils.class
    private String firstName;
    private String lastName;
    private String email;
    private String password;
    private String encryptedPassword;
    private String emailVerificationToken;
    private Boolean emailVerificationStatus = false;

    private List<AddressDto> addresses = new ArrayList<>();

    public UserDto() {
    }
}